### PR TITLE
updated the DeleteBuilding file to list the spaces on hover

### PR DESCRIPTION
**Pull request by fbiko**

### CODE REVIEW

**Review by Ullebror — COMMENTED** [review]
Looks to be working ok, but reading the spaces is a bit difficult when there are many of them. Could there be a way to show them one space per row?
E.g.
`<Tooltip title={`Space(s): ${spaceNames.join(", ")}`} placement="top">` => 
`<Tooltip title= {
          <div style={{ whiteSpace: 'pre-line' }}> Space(s): <br/> { spaceNames.join('\n') }</div>
        } placement="top">`

**Comment by fbiko** [comment]
> Looks to be working ok, but reading the spaces is a bit difficult when there are many of them. Could there be a way to show them one space per row? E.g. `<Tooltip title={`Space(s): ${spaceNames.join(", ")}`} placement="top">` => `<Tooltip title= { <div style={{ whiteSpace: 'pre-line' }}> Space(s): <br/> { spaceNames.join('\n') }</div> } placement="top">`

I agree it is a good idea to list spaces per each row but then i thought the list could be too long if there are many spaces associated. How about increasing the font size instead?

**Comment by Ullebror** [comment]
I think increasing font size would create the same issue as one space per row, if there are many spaces. I think you should really discuss this with alexander (alexfilhag), because now there is pretty much two pull requests for the same thing.

You can find him in the teams group Siba24K with starting a new conversation and then @alex and it will find him, then send him a message in a chat, so you can discuss things privately.

**Review by valju — APPROVED** [review]
Tested. Seems to be improvement to current.

**Pull request merged**
