### PR TITLE
Alert box appears when user is deleted

### PR DESCRIPTION
**Pull request by Sakhi97**
When a user is deleted, an alert box appears, and the user's email address is displayed in the alert box in the message "user email removed."

### CODE REVIEW

**Comment by nicklasstellberg** [comment]
Single user dialog stays open after deleting user.

**Comment by Sakhi97** [comment]
Strange because for me it disappears. Can somebody else check it? the alert box should disappear after 4 seconds

**Comment by Sakhi97** [comment]
The issue with single user dialog is fixed.

**Review by BhaGur — APPROVED** [review]
Tested and works. Single user  box closes after 4 seconds.

**Pull request merged**
