### PR TITLE
Validate add building description update fred

### PR DESCRIPTION
**Pull request by fbiko**

### CODE REVIEW

**Comment by valju** [comment]
Building description is optional, see database. Now this would change it obligatory? Is there anything else this pull-request does?

**Comment by valju** [comment]
It's a bit difficult to coordinate the acceptance of these pull-requests now. I already accepted one, but was it not a final one? Old pull requests should be closed.

I thought you were communicating and coordinating your work? Well, from learning point of course good for both to do. But maybe you can now find one common solution?

**Comment by fbiko** [comment]
> Building description is optional, see database. Now this would change it obligatory? Is there anything else this pull-request does?

Nothing else other than validate the description for building. I will revert my changes and push to keep it optional as it was.

**Comment by valju** [comment]
Ok, so then close the pull request right away. I can do it this time.

**Pull request closed without merging**
