### PR TITLE
Space CSV import updated to include isLowNoise field

### PR DESCRIPTION
**Pull request by hollowdll**
Also fixed space validation time values not being compared correctly by converting time strings to time values. Changed boolean values to accept more truthy values such as "yes" and "y", which are converted to lowercase before being compared.

### CODE REVIEW

**Comment by Ullebror** [comment]
I got this error when pressing the Import Data button: "TypeError: input.match is not a function"
image

**Comment by hollowdll** [comment]
That is weird. I did not get the first error when testing it with the template. I wonder if others get this error? What does it say about the Failed Reasons in that second error when you expand the objects?

**Comment by Ullebror** [comment]
It says that available From is a required field

image

**Comment by hollowdll** [comment]
I updated the code a little and now it should say something like this in case of invalid time format or if time fields have text like "asd123":
image
image

I still can't get the first error you provided with the template. Hopefully somebody else can test this too and tell if it works for them.

**Review by valju — APPROVED** [review]
Nice work! Tested to work ok!

(I had to restart computer to reset the database, but then worked)

**Pull request merged**
